# Generated by Django 3.2.9 on 2022-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=14)),
                ('longitude', models.CharField(max_length=14)),
                ('icon', models.PositiveSmallIntegerField(choices=[('1', 'red_tank'), ('2', 'blue_tank'), ('3', 'sensor'), ('4', 'uav'), ('5', 'blue_soldier'), ('6', 'red_soldier')])),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('mac', models.CharField(max_length=17)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
