# Generated by Django 3.2.9 on 2022-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
