# Generated by Django 3.2.9 on 2022-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0003_alter_dispositivo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='icon',
            field=models.IntegerField(choices=[('1', 'red_tank'), ('2', 'blue_tank'), ('3', 'sensor'), ('4', 'uav'), ('5', 'blue_soldier'), ('6', 'red_soldier')]),
        ),
    ]
